version: '3.3'
services:
 frontend-QS-SaaS:                      # 前端node容器(运行nginx中的Vue项目)
   image: seal/qs-web-saas
   container_name: seal-qs-web-saas    # 容器名
   restart: always                     # 重启策略: 容器退出时总是重启容器
   build:
     context: ../                       # 指定设定上下文根目录，然后以该目录为准指定Dockerfile
     dockerfile: cicd/web/Dockerfile
   environment:
     TZ: Asia/Shanghai
   ports:
     - "8010:80"                      # 映射端口
   networks:
     - custom_net
   external_links:
     - seal-qs-api-saas
#   links:
#     - seal-qs-api-saas
#   depends_on:                          # 依赖于api容器，被依赖容器启动后此web容器才可启动
#     - seal-qs-api-saas

networks:
  custom_net:
    external:
      name: app_net
